# Generated by Django 3.2.21 on 2023-10-17 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20231017_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='date',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created'),
        ),
    ]
