# Generated by Django 3.2.21 on 2023-10-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_auto_20231017_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, null=True)),
                ('receiver', models.CharField(max_length=100)),
                ('message', models.TextField(null=True)),
            ],
        ),
    ]
